import {
	a11yDark,
	a11yLight,
	agate,
	anOldHope,
	androidstudio,
	apathy,
	apprentice,
	arduinoLight,
	arta,
	ascetic,
	ashes,
	atelierCave,
	atelierCaveLight,
	atelierDune,
	atelierDuneLight,
	atelierEstuary,
	atelierEstuaryLight,
	atelierForest,
	atelierForestLight,
	atelierHeath,
	atelierHeathLight,
	atelierLakeside,
	atelierLakesideLight,
	atelierPlateau,
	atelierPlateauLight,
	atelierSavanna,
	atelierSavannaLight,
	atelierSeaside,
	atelierSeasideLight,
	atelierSulphurpool,
	atelierSulphurpoolLight,
	atlas,
	atomOneDark,
	atomOneDarkReasonable,
	atomOneLight
} from 'svelte-highlight/styles';

import {
	base16Github,
	base16IrBlack,
	base16Monokai,
	base16Nord,
	bespin,
	blackMetal,
	blackMetalBathory,
	blackMetalBurzum,
	blackMetalDarkFuneral,
	blackMetalGorgoroth,
	blackMetalImmortal,
	blackMetalKhold,
	blackMetalMarduk,
	blackMetalMayhem,
	blackMetalNile,
	blackMetalVenom,
	brewer,
	bright,
	brogrammer,
	brownPaper,
	brushTrees,
	brushTreesDark
} from 'svelte-highlight/styles';

const themeList = [
	{ id: 21, name: 'Ally Dark', selectTheme: a11yDark },
	{ id: 22, name: 'Ally Light', selectTheme: a11yLight },
	{ id: 23, name: 'Agate', selectTheme: agate },
	{ id: 24, name: 'An Old Hope', selectTheme: anOldHope },
	{ id: 25, name: 'Android Studio', selectTheme: androidstudio },
	{ id: 26, name: 'Apathy', selectTheme: apathy },
	{ id: 27, name: 'Apprentice', selectTheme: apprentice },
	{ id: 28, name: 'Arduino Light', selectTheme: arduinoLight },
	{ id: 29, name: 'Arta', selectTheme: arta },
	{ id: 30, name: 'Ascetic', selectTheme: ascetic },
	{ id: 31, name: 'Ashes', selectTheme: ashes },
	{ id: 32, name: 'Atelier Cave', selectTheme: atelierCave },
	{ id: 33, name: 'Atelier Cave Light', selectTheme: atelierCaveLight },
	{ id: 34, name: 'Atelier Dune', selectTheme: atelierDune },
	{ id: 35, name: 'Atelier Dune Light', selectTheme: atelierDuneLight },
	{ id: 36, name: 'Atelier Estuary', selectTheme: atelierEstuary },
	{ id: 37, name: 'Atelier Estuary Light', selectTheme: atelierEstuaryLight },
	{ id: 38, name: 'Atelier Forest', selectTheme: atelierForest },
	{ id: 39, name: 'Atelier Forest Light', selectTheme: atelierForestLight },
	{ id: 40, name: 'Atelier Health', selectTheme: atelierHeath }
];

export default themeList;
